### ISSUE TITLE
Minimizing windows still shows native non-explorer minimized window bar

### ISSUE THREAD

**Issue by josephs-secureretail** [cairoshell/ManagedShell#108]
I am working on a custom kiosk launcher and using the TasksService to handle minimized windows, so that when a user minimizes a window, the program icon will appear along the bottom of the screen, and the user can then tap or click it to bring it back. 

That part is working properly. However, when I minimize a window after the explorer shell has stopped running, the minimized windows are still showing up along the bottom of the screen as the built-in non-explorer minimized "bar":

![Minimized window screenshot](https://github.com/cairoshell/ManagedShell/assets/171200138/6314144b-1551-4ce7-9be7-b65d1acd1e48)

The code I use to initialize the tasks service is as follows:

    _tasksService = new TasksService(ManagedShell.Common.Enums.IconSize.Medium);
    _tasks = new Tasks(_tasksService);
    _tasks.Initialize();
    
    /* Grab any existing minimized windows. */
    MinimizedWindowList = new ObservableCollection<ApplicationWindow>();
    UpdateMinimizedWindowList();

The "UpdateMinimizedWindowList" just pulls the current list of windows and then makes sure that all that are minimized are in the list I am storing of minimized windows, to display in the main window. 

I am running windows 11 professional edition.

**Comment by dremin** [comment]
A couple things that should help:
- Start your shell after Explorer is closed
- Before creating the TasksService, set `EnvironmentHelper.IsAppRunningAsShell = true`

**Comment by josephs-secureretail** [comment]
Awesome thanks, it seems like that has solved the issue. Funnily enough this only matters for my dev environment where I'm starting it with explorer running and my program is responsible for killing explorer. In production it uses the registry shell key so explorer never actually starts. Either way, it's easy enough to add a quick program restart after killing explorer.
