### ISSUE TITLE
How do i use events for tray icons

### ISSUE THREAD

**Issue by Bluscream** [cairoshell/ManagedShell#64]
I was looking at https://github.com/cairoshell/ManagedShell/wiki/Tray-Service#notification-area-icon-interaction but it does not seem to be able to accept event handlers for "Tray Icon Changed", "Tray Text Changed" and "Tray Baloon Shown"

**Comment by dremin** [comment]
`NotifyIcon` implements `INotifyPropertyChanged`, so you can subscribe to the `PropertyChanged` event, and changes to Icon, Text, etc will raise it.

**Comment by Bluscream** [comment]
Thanks! :3
