### ISSUE TITLE
Which window is on which screen?

### ISSUE THREAD

**Issue by jomedev** [cairoshell/ManagedShell#68]
Is there a way to find out that, for example, window XY is displayed on screen 2?

**Comment by dremin** [comment]
ManagedShell doesn't currently do this (but it is something that should be added). You can use [the `MonitorFromWindow` function](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-monitorfromwindow) to do this.

**Comment by dremin** [comment]
This has been added in #69. Each `ApplicationWindow` has an HMonitor property. If you're using `AppBarWindow`, its `Screen` property also has HMonitor so you can compare.
